### ISSUE TITLE
Percentage calculation is wrong

### ISSUE THREAD

**Issue by fenollp** [wasdennnoch/reddit-anti-gif-bot#10]
https://www.reddit.com/r/blackmagicfuckery/comments/7cse4c/the_underwater_view/dpsaci6/

> This mp4 version is 97.08% smaller than the gif (845.87 KB vs 28.31 MB).

The mp4 is ~3x smaller.

**Comment by wasdennnoch** [comment]
But 0.8MB × 3 isn't 28MB?

**Comment by fenollp** [comment]
Ahah! right :*
Well I did put `~`

**Comment by wasdennnoch** [comment]
Just off by 32 ;)

**Comment by fenollp** [comment]
Still, that mp4 is 3346% smaller than what your bot says. Not just twice.
