### ISSUE TITLE
Skip GIF images that are not animations.

### ISSUE THREAD

**Issue by locoluis** [wasdennnoch/reddit-anti-gif-bot#2]
As it stands, your bot is unable to tell GIF images from GIF animations. This unnecessarily creates single-frame mp4 files from static images.

The following Javascript code accepts a binary string as an argument. It returns `true` if it's a multi-frame GIF, `false` on a single-frame GIF, `undefined` if there's an error. Yes, this is the skeleton of a GIF block decoder, straight from the spec.

Of course, it requires your bot to actually fetch the images from remote servers. I have no experience with Node.js, so I don't know if this is practical, but you may want to make an HTTP HEAD request before fetching the image, in order to avoid 404 errors and also because GIFs larger than 1 MB are most likely animations anyway.

```javascript
function isAnimatedGIF(binaryData)
{
    var offset = 13;
    var layerCount = 0;
    function readblocks()
    {
        var bs = binaryData.charCodeAt(offset) & 0xff;
        while(bs != 0) {
            offset += bs + 1;
            bs = binaryData.charCodeAt(offset) & 0xff;
        }
        offset++;
    }
    if(binaryData.substring(0, 3) != 'GIF') {
        return undefined;
    }
    var lsd = binaryData.charCodeAt(10) & 0xff;
    if(lsd & 128) {
        // Global palette
        offset += 3 * ( 1 << ( ( lsd & 7 ) + 1 ) );
    }
    while(offset < binaryData.length) {
        var blockType = binaryData.charCodeAt(offset) & 0xff;
        if(blockType == 0x3b) {
            // End of stream
            break;
        }
        if(blockType == 0x21) {
            // Extension block
            offset += 2;
            readblocks();
            continue;
        }
        if(blockType == 0x2C) {
            // Image description block
            layerCount++;
            var lsd = binaryData.charCodeAt(offset + 9) & 0xff;
            offset += 11;
            if(lsd & 128) {
                // Local palette
                offset += 3 * ( 1 << ( ( lsd & 7 ) + 1 ) );
            }
            readblocks();
            continue;
        }
        return undefined;
    }
    return layerCount > 1;
}
```

**Comment by wasdennnoch** [comment]
Sorry for the late reply; I decided to be lazy and will only add a size check. A gif size threshold of 750kb seems to not let through any non-animated gifs so far and even when some animated ones get filtered the small file size wouldn't be worth to convert anyways. I'm already working on it and will push the fix soon.

**Comment by thetaCriterion** [comment]
[It's definitely let at least one through](https://www.reddit.com/r/SCP/comments/69okti/im_not_sure_what_you_people_think_about_undertale/dh85obh/).

**Comment by wasdennnoch** [comment]
Well, it's not implemented yet.

**Comment by wasdennnoch** [comment]
Alright, the size check was added in 22a538e38b3e3c84efd7b22b65b8c414fe799e14 and later improved; it's not live yet though since I have to fix some other things as well.

**Comment by wasdennnoch** [comment]
Small images now get skipped and a warning added to lager ones.
