### ISSUE TITLE
gifs ending with ? aren't parsed correctly

### ISSUE THREAD

**Issue by zig-for** [wasdennnoch/reddit-anti-gif-bot#4]
https://www.reddit.com/r/ProgrammerHumor/comments/69j851/css/dh70f74/

**Comment by wasdennnoch** [comment]
Should be fixed with 91bf69fd849131e8ae5629cb2b3d4b6952ac38c6, I still have to test it.

**Comment by wasdennnoch** [comment]
Deployed and working.
