### ISSUE TITLE
Don't post MP4 unless MP4 size is smaller than the GIF size

### ISSUE THREAD

**Issue by kcsaff** [wasdennnoch/reddit-anti-gif-bot#5]
For example [here](https://www.reddit.com/r/stevenuniverse/comments/69yyna/made_a_lil_animation_of_garnet_doing_a_sick_flip/dhadx92/) the MP4 is larger than the GIF, making the text that "mp4s have a drastically smaller file size than gifs" look really silly.

**Comment by wasdennnoch** [comment]
I'll add a size check prior to posting soon (with a threshold of probably 750kb) so that small gifs like that one get ignored. This will also eliminate the problem of bigger file sizes. Because of that I'll close this in favor of #2.
