### ISSUE TITLE
Good robots should have good grammar

### ISSUE THREAD

**Issue by NoMoor** [wasdennnoch/reddit-anti-gif-bot#7]
The bot doesn't seem to have learned human phrasing as of yet.

[Example](https://www.reddit.com/r/bouldering/comments/6e9qtz/breaking_a_decade_long_plateau_bitch_slap_5_v9/di8nym1/): This mp4 version is 1.96 times smaller than the gif (25.54 MB vs 13.06 MB). 

While this is nice in that it has no corner cases, a human would likely phrase this as 'This mp4 is 1/2 the size of the gif (25.54 MB vs 13.06 MB).

(Consider rounding to the nearest integer divisor and rephrasing the reply text)

**Comment by wasdennnoch** [comment]
Changed to percentage with 108949d39b5157dda3489c97a8a1b01336259d50.
